Feat/mutiny new signup
harness/harness-auth-ui pull request #168
Opened 2023-01-04 20:34 UTC by devinder-harness

2023-01-13 11:27 UTC, abhinavrastogi-harness commented on index.html
> +      if (window.isMutinyEnabled === "true" && mutinyToken) {
I'd suggest convert this to a global boolean. it'll be more maintainable. 
eg.
```
window.HARNESS_ENABLE_APPDY_EUM =  "HARNESS_ENABLE_APPDY_EUM_PLACEHOLDER" === "true";
```

2023-01-13 11:27 UTC, abhinavrastogi-harness commented on index.html
> +        const mutinyClient = document.createElement("script");
can we make this async/defer? analytics/tracking scripts should never block the app load

2023-01-13 11:27 UTC, abhinavrastogi-harness commented on src/static/images/ancestory.svg
> +<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 149 28"><path fill-rule="evenodd" clip-rule="evenodd" d="M43.556 11.645c-1.652.208-2.684.692-3.372 1.385-.55.554-.826 1.246-.826 1.938
are the svg's optimised?
also can we check if the png will be smaller for these semi-complex logos?

2023-01-13 11:56 UTC, devinder-harness commented on index.html
> +        const mutinyClient = document.createElement("script");
no we cannot it as it will cause a flicker on screen

2023-01-13 11:56 UTC, devinder-harness commented on src/static/images/ancestory.svg
> +<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 149 28"><path fill-rule="evenodd" clip-rule="evenodd" d="M43.556 11.645c-1.652.208-2.684.692-3.372 1.385-.55.554-.826 1.246-.826 1.938
Yes let m check

2023-01-13 13:23 UTC, devinder-harness commented on src/static/images/ancestory.svg
> +<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 149 28"><path fill-rule="evenodd" clip-rule="evenodd" d="M43.556 11.645c-1.652.208-2.684.692-3.372 1.385-.55.554-.826 1.246-.826 1.938
Yes these are optimized from svgo

2023-01-16 10:47 UTC, kapilkumawat86 approved these changes

2023-01-16 10:49 UTC, vkbansal-harness approved these changes

2023-01-16 10:50 UTC, kapilkumawat86 requested changes
Lets also add enable disable

2023-01-16 10:57 UTC, kapilkumawat86 approved these changes

2023-01-16 11:24 UTC, abhinavrastogi-harness approved these changes

2023-01-17 04:47 UTC, kapilkumawat86 approved these changes

2023-01-19 11:18 UTC, merged