feat: [PL-42158]: accept and show error message for unauthorized message
harness/harness-auth-ui pull request #229
Opened 2023-11-04 04:37 UTC by namanharness

2023-11-06 07:13 UTC, namanharness commented on src/app.tsx
> +      message?.code === "NOT_WHITELISTED_IP" || message?.code === "UNAUTHORIZED"
Error message codes from BE for 401 error

2023-11-06 07:13 UTC, namanharness commented on src/pages/SignIn/SignIn.tsx
> +      case "NOT_WHITELISTED_IP_MESSAGE_ERROR": {
need to update this from Harness Core UI as well as code message there need to be updated.

2023-11-06 07:13 UTC, namanharness commented on src/pages/SignIn/SignIn.tsx
> +      case "MARK_FOR_DELETION_ERROR": {
need to add in harness core ui.

2023-11-06 07:40 UTC, mayankVermaHarness commented on src/pages/SignIn/SignIn.tsx
> +      case "MARK_FOR_DELETION_ERROR": {
Let's make this generic. There may be other cases for Unauthorized as well.

```suggestion
      case "unauth": {
```

2023-11-06 08:19 UTC, namanharness commented on src/pages/SignIn/SignIn.tsx
> +      case "MARK_FOR_DELETION_ERROR": {
so under `unauth` ErrorCode, the session storage key would be something related to mark for deletion or that would be generic as well like `unauth`

2023-11-06 08:22 UTC, mayankVermaHarness commented on src/pages/SignIn/SignIn.tsx
> +      case "MARK_FOR_DELETION_ERROR": {
It will also be generic, because we don't have a separate differentiator for MARK FOR DELETION.

2023-11-07 14:06 UTC, mayankVermaHarness commented on src/pages/SignIn/SignIn.tsx
> +      case "UNAUTHORIZED_ERROR": {
This may change as per ErrorCode changes in https://github.com/harness/harness-core-ui/pull/18815

2023-11-21 15:39 UTC, mayankVermaHarness approved these changes
This is strongly tied to the NG-UI PR: https://github.com/harness/harness-core-ui/pull/18815.

They should be released together.

2023-11-21 22:11 UTC, abhinavrastogi-harness requested changes

2023-11-21 22:11 UTC, abhinavrastogi-harness commented on src/pages/SignIn/SignIn.tsx
> +        const message = sessionStorage.getItem("UNAUTHORIZED");
when are you setting this to session storage?
also, why is the key just "UNAUTHORIZED"?

2023-11-21 22:11 UTC, abhinavrastogi-harness commented on src/pages/SignIn/SignIn.tsx
> +          toast.error("Unauthorized Login.", {
not a useful error message. check with product team for the correct message.

2023-11-21 22:11 UTC, abhinavrastogi-harness commented on src/app.tsx
> +      message?.code === "NOT_WHITELISTED_IP" || message?.code === "UNAUTHORIZED"
this is too broad of a classification. you need a special error code to handle users marked for deletion.
In what all scenarios can the BE return this error code?

2023-11-21 22:11 UTC, abhinavrastogi-harness commented on src/app.tsx
> +const getUnauthorizedErrorMessage = (res: any): any => {
to cover multiple usecases, a better generic name would be `getErrorMessage`

2023-11-21 22:12 UTC, abhinavrastogi-harness commented
No tests added/changed for this?

2023-11-21 22:19 UTC, namanharness commented on src/app.tsx
> +      message?.code === "NOT_WHITELISTED_IP" || message?.code === "UNAUTHORIZED"
Currently BE returns this Error code only when User is marked for Deletion.

2023-11-23 15:36 UTC, mayankVermaHarness commented on src/pages/SignIn/SignIn.tsx
> +          toast.error("Unauthorized Login.", {
As of today, `UNAUTHORIZED` handles only the use-case for "account marked for deletion"—which will always have a `message`.

The `else` here manages the error message just-in-case backend doesn't respond with one—which isn't very likely.

@namanharness Let's change this generic error message in `else` block to:
`Authentication failed. Please login again, or contact your admin.`

2023-11-23 18:01 UTC, namanharness commented
> No tests added/changed for this?

Tests are added from harness-core-ui @abhinavrastogi-harness

2023-11-27 17:50 UTC, abhinavrastogi-harness approved these changes

2023-11-28 13:06 UTC, merged

2023-11-29 12:09 UTC, mayankVermaHarness commented on src/app.tsx
>                toast.error(msg);
Increase to 10 seconds